import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout from '../components/layout.js'

import styles from '../styles/Landing.module.css'

export default function Landing() {
  return (
    <div>
      <Head>
        <title>UCHI</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      <Layout>
        <div className={styles.visualContainer}>
          <div className={styles.visualChocolate80}>
            <img src="/landing-visual.png" alt="A person cheers next to their home." />
          </div>
          <div className={styles.visualVanillaToasted}>
            <p className="brand noMB">U&#8226;CHI</p>
            <p className={styles.phonetic}>/ <span className={styles.overline}>oo</span>CH<span className={styles.overline}>e</span> /</p>
            <p className={styles.definition}>make a house your home</p>
          </div>
        </div>
        <div className={styles.pageContent}>
          <h1 className={styles.title}><span className={styles.brand}>UCHI</span></h1>
          <p className={styles.info}>Approximately two-thirds of first-time American homeowners ignore home maintenance
          until parts of their home begin to malfunction, resulting in unexpected expenses.
          To mitigate homebuyer’s regret caused by being unprepared for home maintenance,
          UCHI organizes maintenance tasks relevant to each home. With UCHI’s recommendations
          and reminders to stay up-to-date with home maintenance tasks, first-time homeowners
          are able to protect their investments and better care for their homes.
          </p>
          <hr className={styles.hr} />
          <h2>Key Features</h2>
          <div className={styles.keyFeaturesContainer}>
            <KeyFeature name="Education" desc="Provide education and guidance." img="/images/key-features/education.png" />
            <KeyFeature name="Task Tracker" desc="Track and notify about tasks." img="/images/key-features/task-tracker.png" />
            <KeyFeature name="Customizability" desc="Personalize a one-stop home maintenance experience." img="/images/key-features/customizability.png" />
          </div>
          <h2>Demonstration Video</h2>
          <h2>Team KozyKrew</h2>
          <div className={styles.profilesContainer}>
            <TeamProfile name="Ariane Apigo" roles="UX Designer, Front-end Developer" img="/images/team/ariane.png" linkedin="" />
            <TeamProfile name="Rachel Chung" roles="UX Designer, Researcher" img="/images/team/rachel.png" linkedin="" />
            <TeamProfile name="John-Luke Dokupil" roles="Data Scientist, Researcher" img="/images/team/johnluke.png" linkedin="" />
            <TeamProfile name="Ratul Jain" roles="Data Scientist, Back-end Developer" img="/images/team/ratul.png" linkedin="" />
          </div>
          <h2>Project Status</h2>
          <p className={styles.info}>UCHI started as a student-driven Capstone project
           for the Information School at the University of Washington, Winter/Spring 2022.
           As of May 25, 2022, UCHI will transition to be an <span className={styles.bodybold}>open source project</span> for future
           iSchool Capstone teams to further develop.
          </p>
        </div>
        <div className={styles.visualContainer}>
          <div className={styles.visualMint80}>
            <h1 className="noMB">Try <span className="brand">UCHI</span> today!</h1>
          </div>
          <div className={styles.visualOrange60}>
            <p className={styles.signup}>Sign Up</p>
            <img src="/icons/arrowcircle_right_line_dark.svg" alt="Sign Up Today" />
          </div>
        </div>
        <div className={styles.footer}>
          <p className="brand">UCHI</p>
          <img className={styles.ischool} src="/iSchoolLogo_UCHI_TextLight.png" alt="University of Washington Information School" />
          <p>&copy; 2022 UCHI. All rights reserved.</p>
        </div>
      </Layout>
    </div>
  )
  // MVP below
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>UCHI</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //
  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <span className="brand">UCHI</span>!
  //       </h1>
  //
  //       <p className={styles.description}>
  //         View our MVP at {' '}
  //         <code className={styles.code}><Link href="/dashboard">pages/dashboard.js</Link></code>
  //       </p>
  //
  //       <p>We currently have only developed a mobile version of <span className="brand">UCHI</span>.</p>
  //       <p>Please resize your window to a width of 375 pixels to view <span className="brand">UCHI</span> properly.</p>
  //
  //     </main>
  //
  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // )
}

function KeyFeature(props) {
  return (
    <div className={styles.keyFeaturesContainer}>
      <div className={styles.bubbleContainer}>
        <div className={styles.keyFeatureBubble}>
          <div>
            <img className={styles.keyFeatureImg} src={props.img} alt={props.name} />
          </div>
        </div>
      </div>
      <h3>{props.name}</h3>
      <p>{props.desc}</p>
    </div>
  )
}

function TeamProfile(props) {
  return (
    <div className={styles.profileContainer}>
      <img className={styles.memberProfileImg} src={props.img} alt={props.name} />
      <div className={styles.profileDetailsContainer}>
        <h3>{props.name}</h3>
        <p>{props.roles}</p>
        <a href={props.linkedin}>
          <img className={styles.linkedIn} src="/icons/linkedin_dark.svg" alt={props.name + "&#39;s LinkedIn Profile"} />
        </a>
      </div>
    </div>
  )
}

// ---------- some resources that came with default next.js app ----------
// <div className={styles.grid}>
//   <a href="https://nextjs.org/docs" className={styles.card}>
//     <h2>Documentation &rarr;</h2>
//     <p>Find in-depth information about Next.js features and API.</p>
//   </a>
//
//   <a href="https://nextjs.org/learn" className={styles.card}>
//     <h2>Learn &rarr;</h2>
//     <p>Learn about Next.js in an interactive course with quizzes!</p>
//   </a>
//
//   <a
//     href="https://github.com/vercel/next.js/tree/canary/examples"
//     className={styles.card}
//   >
//     <h2>Examples &rarr;</h2>
//     <p>Discover and deploy boilerplate example Next.js projects.</p>
//   </a>
//
//   <a
//     href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//     className={styles.card}
//   >
//     <h2>Deploy &rarr;</h2>
//     <p>
//       Instantly deploy your Next.js site to a public URL with Vercel.
//     </p>
//   </a>
// </div>
